<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PricingPlan;

class PricingPlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name_ar' => 'الأساسي',
                'name_en' => 'Basic',
                'slug' => 'basic',
                'description_ar' => 'مثالي للعيادات الصغيرة التي تبدأ رحلة التحول الرقمي',
                'description_en' => 'Perfect for small clinics starting their digital transformation',
                'monthly_price' => 799,
                'yearly_price' => 7670,
                'currency' => 'EGP',
                'is_popular' => false,
                'is_custom' => false,
                'features_ar' => [
                    'بوابة المدير + السكرتيرة + الموقع العام',
                    'إدارة المرضى (حتى 500 مريض)',
                    'نظام الحجوزات والمواعيد',
                    'الفواتير والمدفوعات الأساسية',
                    'لوحة تحكم بإحصائيات أساسية',
                    'طريقة دفع واحدة',
                    'دعم فني عبر البريد الإلكتروني',
                    'لغة واحدة (عربي أو إنجليزي)',
                    '3 مستخدمين كحد أقصى',
                    'قالب PDF للفاتورة فقط',
                    'نسخ احتياطي أسبوعي',
                ],
                'features_en' => [
                    'Admin + Secretary + Public Website portals',
                    'Patient management (up to 500 patients)',
                    'Bookings & appointments system',
                    'Basic invoicing & payments',
                    'Dashboard with basic statistics',
                    'Single payment method',
                    'Email support',
                    'Single language (Arabic or English)',
                    'Up to 3 users',
                    'Invoice PDF template only',
                    'Weekly backup',
                ],
                'modules_included' => ['patients','bookings','invoices','payments','website'],
                'max_users' => 3,
                'max_patients' => 500,
                'support_level' => 'email',
                'display_order' => 1,
            ],
            [
                'name_ar' => 'الاحترافي',
                'name_en' => 'Professional',
                'slug' => 'professional',
                'description_ar' => 'الخيار الأمثل للعيادات المتوسطة التي تريد تجربة متكاملة',
                'description_en' => 'The ideal choice for medium clinics wanting a complete experience',
                'monthly_price' => 1599,
                'yearly_price' => 15350,
                'currency' => 'EGP',
                'is_popular' => true,
                'is_custom' => false,
                'features_ar' => [
                    'كل ميزات الخطة الأساسية +',
                    'بوابة الطبيب + بوابة المريض',
                    'مرضى غير محدودين',
                    'نظام CRM متكامل (عملاء محتملين، أنبوب مبيعات، تسلسلات آلية)',
                    'نظام المحفظة الإلكترونية للمرضى',
                    'أكواد الخصم والعروض الترويجية',
                    'إشعارات البريد الإلكتروني والتذكيرات',
                    'الدردشة الداخلية بين الموظفين',
                    'شريط الأوامر السريع (Cmd+K)',
                    'نظام الإشعارات الفورية',
                    'قوالب PDF (فاتورة + وصفة + إيصال)',
                    'ثنائي اللغة (عربي + إنجليزي)',
                    '10 مستخدمين كحد أقصى',
                    'الإشعارات الدائنة (Credit Notes)',
                    'استبيان رضا المرضى مع NPS',
                    'إدارة المصروفات',
                    'سجل تدقيق أساسي',
                    'دعم فني عبر الهاتف والبريد',
                    'نسخ احتياطي يومي',
                ],
                'features_en' => [
                    'Everything in Basic plan +',
                    'Doctor Portal + Patient Portal',
                    'Unlimited patients',
                    'Full CRM system (leads, pipeline, sequences)',
                    'Patient e-wallet system',
                    'Discount codes & promotions',
                    'Email notifications & reminders',
                    'Internal team chat',
                    'Command palette (Cmd+K)',
                    'Real-time notifications',
                    'PDF templates (invoice + prescription + receipt)',
                    'Bilingual (Arabic + English)',
                    'Up to 10 users',
                    'Credit notes management',
                    'Patient satisfaction surveys with NPS',
                    'Expense management',
                    'Basic audit log',
                    'Phone & email support',
                    'Daily backup',
                ],
                'modules_included' => ['patients','bookings','invoices','payments','website','crm','wallet','discounts','chat','notifications','prescriptions','satisfaction','expenses'],
                'max_users' => 10,
                'max_patients' => null,
                'support_level' => 'phone',
                'display_order' => 2,
            ],
            [
                'name_ar' => 'المتقدم',
                'name_en' => 'Enterprise',
                'slug' => 'enterprise',
                'description_ar' => 'الحل الشامل للمراكز الطبية التي تريد كل شيء',
                'description_en' => 'The complete solution for medical centers that want everything',
                'monthly_price' => 2999,
                'yearly_price' => 28790,
                'currency' => 'EGP',
                'is_popular' => false,
                'is_custom' => false,
                'features_ar' => [
                    'كل ميزات الخطة الاحترافية +',
                    'بوابة مدير الموقع (39 واجهة كاملة)',
                    'وحدة طب الأسنان الكاملة:',
                    '  — مخطط أسنان تفاعلي SVG بترقيم FDI (32 سن × 5 أسطح × 9 حالات)',
                    '  — خطط العلاج مع شريط تقدم (4 أولويات، 5 حالات)',
                    '  — مخطط اللثة Periodontal (6 قياسات لكل سن)',
                    '  — 6 أنواع أشعة (بانوراما، حول ذروية، جناح العض، سيفالومترية، CBCT، إطباقية)',
                    '  — طلبات المعمل (8 أنواع قطع، اختيار اللون والمادة، 6 مراحل)',
                    '  — موافقات رقمية بتوقيع إلكتروني',
                    '  — مقارنات قبل/بعد العلاج',
                    '  — قواعد متابعة ذكية وتذكيرات تلقائية',
                    'وحدة الموارد البشرية الكاملة:',
                    '  — ملفات موظفين شاملة مع هيكل رواتب (أساسي + سكن + نقل + بدلات)',
                    '  — تسجيل حضور بتحديد GPS',
                    '  — مسيرات رواتب (12+ حقل مالي) مع سير موافقة',
                    '  — إدارة الإجازات والورديات والأقسام',
                    '  — نظام السلف والعقوبات المالية',
                    'وحدة التأمين الطبي الكاملة:',
                    '  — إدارة شركات التأمين والخطط (6 فئات VIP-E)',
                    '  — 6 أعلام تغطية مستقلة (أسنان، جلدية، تجميل، مختبر، أشعة، أدوية)',
                    '  — مطالبات تأمينية بسير عمل 8 مراحل',
                    'وحدة المخزون الكاملة:',
                    '  — إدارة مواد بـ SKU مع إعادة طلب تلقائي',
                    '  — تنبيهات مخزون منخفض وانتهاء صلاحية',
                    '  — إدارة موردين وأوامر شراء (7 مراحل)',
                    'مستخدمين غير محدودين',
                    '8 قوالب PDF كاملة (فاتورة، وصفة، مخطط أسنان، خطة علاج، موافقة، إيصالات، مسير راتب)',
                    'تكامل تتبع كامل (GTM, GA4, Facebook, TikTok, Snapchat, Twitter Pixels)',
                    'نظام RBAC كامل بأكثر من 80 صلاحية دقيقة',
                    'سجل تدقيق شامل + سجل وصول طبي حساس',
                    'سلة محذوفات مع استعادة (Soft Delete)',
                    'دعم فني ذهبي 24/7',
                    'نسخ احتياطي كل 6 ساعات',
                ],
                'features_en' => [
                    'Everything in Professional plan +',
                    'Webmaster Portal (39 full interfaces)',
                    'Complete Dental Module:',
                    '  — Interactive SVG dental chart with FDI numbering (32 teeth x 5 surfaces x 9 conditions)',
                    '  — Treatment plans with progress bar (4 priorities, 5 statuses)',
                    '  — Periodontal chart (6 measurements per tooth)',
                    '  — 6 X-ray types (panoramic, periapical, bitewing, cephalometric, CBCT, occlusal)',
                    '  — Lab orders (8 item types, shade & material selection, 6-stage workflow)',
                    '  — Digital consent with e-signature',
                    '  — Before/after treatment comparisons',
                    '  — Smart follow-up rules & auto-reminders',
                    'Complete HR Module:',
                    '  — Full employee profiles with salary structure (basic + housing + transport + allowances)',
                    '  — GPS attendance tracking',
                    '  — Payroll (12+ financial fields) with approval workflow',
                    '  — Leave, shift & department management',
                    '  — Advances & penalties system',
                    'Complete Insurance Module:',
                    '  — Insurance companies & plans (6 classes VIP-E)',
                    '  — 6 independent coverage flags (dental, derma, cosmetic, lab, xray, medication)',
                    '  — Insurance claims with 8-stage workflow',
                    'Complete Inventory Module:',
                    '  — Supply management with SKU & auto-reorder',
                    '  — Low stock & expiry alerts',
                    '  — Supplier & purchase order management (7-stage workflow)',
                    'Unlimited users',
                    '8 complete PDF templates (invoice, prescription, dental chart, treatment plan, consent, receipts, payslip)',
                    'Full tracking integration (GTM, GA4, Facebook, TikTok, Snapchat, Twitter)',
                    'Full RBAC with 80+ granular permissions',
                    'Complete audit log + medical access log',
                    'Trash with restore (Soft Delete)',
                    'Gold 24/7 support',
                    'Backup every 6 hours',
                ],
                'modules_included' => ['patients','bookings','invoices','payments','website','crm','wallet','discounts','chat','notifications','prescriptions','satisfaction','expenses','dental','hr','insurance','inventory','webmaster','rbac','audit'],
                'max_users' => null,
                'max_patients' => null,
                'support_level' => 'priority',
                'display_order' => 3,
            ],
            [
                'name_ar' => 'مخصص',
                'name_en' => 'Custom',
                'slug' => 'custom',
                'description_ar' => 'حلول مصممة خصيصاً للمراكز الطبية الكبيرة والمستشفيات',
                'description_en' => 'Tailored solutions for large medical centers and hospitals',
                'monthly_price' => 0,
                'yearly_price' => 0,
                'currency' => 'EGP',
                'is_popular' => false,
                'is_custom' => true,
                'features_ar' => [
                    'كل ميزات الخطة المتقدمة +',
                    'تركيب على سيرفر خاص (On-Premise)',
                    'تطوير ميزات حسب الطلب',
                    'تكامل مع أنظمة خارجية (ERP, LIS, RIS, PACS)',
                    'تدريب شامل لفريق العمل',
                    'مدير حساب مخصص',
                    'اتفاقية مستوى خدمة SLA مخصصة',
                    'White-Label (تغيير الهوية والشعار)',
                    'تقارير مخصصة حسب الطلب',
                    'API مفتوح للتكامل',
                    'أولوية في الدعم الفني',
                    'استشارات تقنية مجانية',
                ],
                'features_en' => [
                    'Everything in Enterprise plan +',
                    'On-Premise installation',
                    'Custom feature development',
                    'External system integration (ERP, LIS, RIS, PACS)',
                    'Comprehensive team training',
                    'Dedicated account manager',
                    'Custom SLA agreement',
                    'White-Label (custom branding)',
                    'Custom reports on demand',
                    'Open API for integration',
                    'Priority technical support',
                    'Free technical consultations',
                ],
                'modules_included' => ['all'],
                'max_users' => null,
                'max_patients' => null,
                'support_level' => 'dedicated',
                'display_order' => 4,
            ],
        ];

        foreach ($plans as $plan) {
            PricingPlan::updateOrCreate(
                ['slug' => $plan['slug']],
                $plan
            );
        }
    }
}
